Add link descriptions #13
ubc-lib-geo/creating-index-maps pull request #23
Opened 2022-11-19 00:10 UTC by brettdimond

Provide descriptions of links under 'More information' section of 'What are index maps' page.

Remove reference to Jon Jab and Chris Thiry's WAML 2018 workshop material, as the link appears to be broken: https://ucsb.app.box.com/v/WAMLindexes/folder/53136056329.

2022-11-22 17:08 UTC, ect123 commented on content/what-are-index-maps.md
> +- [OpenIndexMaps GitHub organization](https://github.com/OpenIndexMaps): Similar to the above clearinghouse, this GitHub organization serves as an open location to access (and contribute) GeoJSON fil
I recommend rewording to: "this GitHub organization serves as an open metadata collection of OpenIndexMaps GeoJSON files."

2022-11-22 17:09 UTC, ect123 requested changes
Looks great! I recommended one alteration to your proposed text.

2022-11-22 17:54 UTC, brettdimond commented on content/what-are-index-maps.md
> +- [OpenIndexMaps GitHub organization](https://github.com/OpenIndexMaps): Similar to the above clearinghouse, this GitHub organization serves as an open location to access (and contribute) GeoJSON fil
Added new commit to this branch with the recommended change.

2023-01-25 22:00 UTC, ect123 approved these changes

2023-01-25 22:00 UTC, merged